apiVersion: v1
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush         5
        Grace         120
        Log_Level     info
        Log_File      /var/log/fluentbit.log
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_PORT     2020


    [INPUT]
        Name             tail
        Alias            kube_containers_kube-system
        Tag              kube_<namespace_name>_<pod_name>_<container_name>
        Tag_Regex        (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
        Path             /var/log/containers/*_kube-system_*.log
        DB               /var/run/google-fluentbit/pos-files/flb_kube_kube-system.db
        Buffer_Max_Size  1MB
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
        Refresh_Interval 5

    [INPUT]
        Name             tail
        Alias            kube_containers_istio-system
        Tag              kube_<namespace_name>_<pod_name>_<container_name>
        Tag_Regex        (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
        Path             /var/log/containers/*_istio-system_*.log
        DB               /var/run/google-fluentbit/pos-files/flb_kube_istio-system.db
        Buffer_Max_Size  1MB
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
        Refresh_Interval 5

    [INPUT]
        Name             tail
        Alias            kube_containers_knative-serving
        Tag              kube_<namespace_name>_<pod_name>_<container_name>
        Tag_Regex        (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
        Path             /var/log/containers/*_knative-serving_*.log
        DB               /var/run/google-fluentbit/pos-files/flb_kube_knative-serving.db
        Buffer_Max_Size  1MB
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
        Refresh_Interval 5

    [INPUT]
        Name             tail
        Alias            kube_containers_gke-system
        Tag              kube_<namespace_name>_<pod_name>_<container_name>
        Tag_Regex        (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
        Path             /var/log/containers/*_gke-system_*.log
        DB               /var/run/google-fluentbit/pos-files/flb_kube_gke-system.db
        Buffer_Max_Size  1MB
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
        Refresh_Interval 5

    [INPUT]
        Name             tail
        Alias            kube_containers_config-management-system
        Tag              kube_<namespace_name>_<pod_name>_<container_name>
        Tag_Regex        (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
        Path             /var/log/containers/*_config-management-system_*.log
        DB               /var/run/google-fluentbit/pos-files/flb_kube_config-management-system.db
        Buffer_Max_Size  1MB
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
        Refresh_Interval 5



    [INPUT]
        Name             tail
        Alias            kube_containers
        Tag              kube_<namespace_name>_<pod_name>_<container_name>
        Tag_Regex        (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
        Path             /var/log/containers/*.log
        Exclude_Path     /var/log/containers/*_kube-system_*.log,/var/log/containers/*_istio-system_*.log,/var/log/containers/*_knative-serving_*.log,/var/log/containers/*_gke-system_*.log,/var/log/containers/*_config-management-system_*.log
        DB               /var/run/google-fluentbit/pos-files/flb_kube.db
        Buffer_Max_Size  1MB
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
        Refresh_Interval 5


    # This input plugin is used to collect the logs located inside the /var/log
    # directory of a Cloud Run on GKE / Knative container. Knative mounts
    # an emptyDir volume named 'knative-var-log' inside the user container and
    # if collection is enabled it creates a symbolic link inside another
    # emptyDir named 'knative-internal' that contains the information needed for
    # Kubernetes metadata enrichment.
    #
    # Concretely, on the host the symbolic link is:
    # /var/lib/kubelet/pods/<POD_ID>/volumes/kubernetes.io~empty-dir/knative-internal/<NAMESPACE_NAME>_<POD_NAME>_<CONTAINER_NAME>
    # ->
    # /var/lib/kubelet/pods/<POD_ID>/volumes/kubernetes.io~empty-dir/knative-var-log
    [INPUT]
        Name             tail
        Alias            knative
        Tag              kube_<namespace_name>_<pod_name>_<container_name>
        Tag_Regex        \/var\/lib\/kubelet\/pods\/.+\/(?<namespace_name>[^_]+)_(?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<id>[\-a-z0-9]+)\/(?<runtime>[a-z]+)\.log
        Path             /var/lib/kubelet/pods/*/volumes/kubernetes.io~empty-dir/knative-internal/**/*/**/*
        DB               /var/run/google-fluentbit/pos-files/knative.db
        Buffer_Max_Size  1MB
        Mem_Buf_Limit    1MB
        Skip_Long_Lines  On
        Refresh_Interval 5

    [FILTER]
        Name         parser
        Match        kube_*
        Key_Name     log
        Reserve_Data True
        Parser       docker
        Parser       containerd

    # This input is used  to watch changes to Kubernetes pod log files live in the
    # directory /var/log/pods/NAMESPACE_NAME_UID. The file name is used to
    # capture the pod namespace, name and runtime name.


    [INPUT]
        Name             tail
        Alias            gvisor_kube-system
        Tag              kube-pod_<namespace_name>_<pod_name>_<runtime>
        Tag_Regex        \/var\/log\/pods\/(?<namespace_name>[^_]+)_(?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<id>[\-a-z0-9]+)\/(?<runtime>[a-z]+)\.log
        Path             /var/log/pods/kube-system_*/*
        DB               /var/run/google-fluentbit/pos-files/gvisor_kube-system.db
        Buffer_Max_Size  1MB
        Mem_Buf_Limit    1MB
        Skip_Long_Lines  On
        Refresh_Interval 5

    [INPUT]
        Name             tail
        Alias            gvisor_istio-system
        Tag              kube-pod_<namespace_name>_<pod_name>_<runtime>
        Tag_Regex        \/var\/log\/pods\/(?<namespace_name>[^_]+)_(?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<id>[\-a-z0-9]+)\/(?<runtime>[a-z]+)\.log
        Path             /var/log/pods/istio-system_*/*
        DB               /var/run/google-fluentbit/pos-files/gvisor_istio-system.db
        Buffer_Max_Size  1MB
        Mem_Buf_Limit    1MB
        Skip_Long_Lines  On
        Refresh_Interval 5

    [INPUT]
        Name             tail
        Alias            gvisor_knative-serving
        Tag              kube-pod_<namespace_name>_<pod_name>_<runtime>
        Tag_Regex        \/var\/log\/pods\/(?<namespace_name>[^_]+)_(?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<id>[\-a-z0-9]+)\/(?<runtime>[a-z]+)\.log
        Path             /var/log/pods/knative-serving_*/*
        DB               /var/run/google-fluentbit/pos-files/gvisor_knative-serving.db
        Buffer_Max_Size  1MB
        Mem_Buf_Limit    1MB
        Skip_Long_Lines  On
        Refresh_Interval 5

    [INPUT]
        Name             tail
        Alias            gvisor_gke-system
        Tag              kube-pod_<namespace_name>_<pod_name>_<runtime>
        Tag_Regex        \/var\/log\/pods\/(?<namespace_name>[^_]+)_(?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<id>[\-a-z0-9]+)\/(?<runtime>[a-z]+)\.log
        Path             /var/log/pods/gke-system_*/*
        DB               /var/run/google-fluentbit/pos-files/gvisor_gke-system.db
        Buffer_Max_Size  1MB
        Mem_Buf_Limit    1MB
        Skip_Long_Lines  On
        Refresh_Interval 5

    [INPUT]
        Name             tail
        Alias            gvisor_config-management-system
        Tag              kube-pod_<namespace_name>_<pod_name>_<runtime>
        Tag_Regex        \/var\/log\/pods\/(?<namespace_name>[^_]+)_(?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<id>[\-a-z0-9]+)\/(?<runtime>[a-z]+)\.log
        Path             /var/log/pods/config-management-system_*/*
        DB               /var/run/google-fluentbit/pos-files/gvisor_config-management-system.db
        Buffer_Max_Size  1MB
        Mem_Buf_Limit    1MB
        Skip_Long_Lines  On
        Refresh_Interval 5



    [INPUT]
        Name             tail
        Alias            gvisor
        Tag              kube-pod_<namespace_name>_<pod_name>_<runtime>
        Tag_Regex        \/var\/log\/pods\/(?<namespace_name>[^_]+)_(?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<id>[\-a-z0-9]+)\/(?<runtime>[a-z]+)\.log
        Exclude_Path     /var/log/pods/kube-system_*/*,/var/log/pods/istio-system_*/*,/var/log/pods/knative-serving_*/*,/var/log/pods/gke-system_*/*,/var/log/pods/config-management-system_*/*
        Path             /var/log/pods/*/*.log
        DB               /var/run/google-fluentbit/pos-files/gvisor.db
        Buffer_Max_Size  1MB
        Mem_Buf_Limit    1MB
        Skip_Long_Lines  On
        Refresh_Interval 5


    # Example:
    # Dec 21 23:17:22 gke-foo-1-1-4b5cbd14-node-4eoj startupscript: Finished running startup script /var/run/google.startup.script
    [INPUT]
        Name   tail
        Parser syslog
        Path   /var/log/startupscript.log
        DB     /var/run/google-fluentbit/pos-files/startupscript.db
        Alias  startupscript
        Tag    startupscript

    # Logs from anetd for policy action
    [INPUT]
        Name             tail
        Parser           network-log
        Alias            policy-action
        Tag              policy-action
        Path             /var/log/network/policy_action.log
        DB               /var/run/google-fluentbit/pos-files/policy-action.db
        Skip_Long_Lines  On
        Refresh_Interval 5

    # Example:
    # I1118 21:26:53.975789       6 proxier.go:1096] Port "nodePort for kube-system/default-http-backend:http" (:31429/tcp) was open before and is still needed
    [INPUT]
        Name            tail
        Alias           kube-proxy
        Tag             kube-proxy
        Path            /var/log/kube-proxy.log
        DB              /var/run/google-fluentbit/pos-files/kube-proxy.db
        Buffer_Max_Size 1MB
        Mem_Buf_Limit   1MB
        Parser          glog

    # Logs from systemd-journal for interesting services.
    [INPUT]
        Name            systemd
        Alias           docker
        Tag             docker
        Systemd_Filter  _SYSTEMD_UNIT=docker.service
        Path            /var/log/journal
        DB              /var/run/google-fluentbit/pos-files/docker.db
        Buffer_Max_Size 1MB
        Mem_Buf_Limit   1MB

    [INPUT]
        Name            systemd
        Alias           container-runtime
        Tag             container-runtime
        Systemd_Filter  _SYSTEMD_UNIT=containerd.service
        Path            /var/log/journal
        DB              /var/run/google-fluentbit/pos-files/container-runtime.db
        Buffer_Max_Size 1MB
        Mem_Buf_Limit   1MB

    [INPUT]
        Name            systemd
        Alias           kubelet
        Tag             kubelet
        Systemd_Filter  _SYSTEMD_UNIT=kubelet.service
        Path            /var/log/journal
        DB              /var/run/google-fluentbit/pos-files/kubelet.db
        Buffer_Max_Size 1MB
        Mem_Buf_Limit   1MB

    # kube-node-installation, kube-node-configuration, and kube-logrotate are
    # oneshots, but it's extremely valuable to have their logs on Stackdriver
    # as they can diagnose critical issues with node startup.
    [INPUT]
        Name            systemd
        Alias           kube-node-installation
        Tag             kube-node-installation
        Systemd_Filter  _SYSTEMD_UNIT=kube-node-installation.service
        Path            /var/log/journal
        DB              /var/run/google-fluentbit/pos-files/kube-node-installation.db
        Buffer_Max_Size 1MB
        Mem_Buf_Limit   1MB

    [INPUT]
        Name            systemd
        Alias           kube-node-configuration
        Tag             kube-node-configuration
        Systemd_Filter  _SYSTEMD_UNIT=kube-node-configuration.service
        Path            /var/log/journal
        DB              /var/run/google-fluentbit/pos-files/kube-node-configuration.db
        Buffer_Max_Size 1MB
        Mem_Buf_Limit   1MB

    [INPUT]
        Name            systemd
        Alias           kube-logrotate
        Tag             kube-logrotate
        Systemd_Filter  _SYSTEMD_UNIT=kube-logrotate.service
        Path            /var/log/journal
        DB              /var/run/google-fluentbit/pos-files/kube-logrotate.db
        Buffer_Max_Size 1MB
        Mem_Buf_Limit   1MB

    [INPUT]
        Name            systemd
        Alias           node-problem-detector
        Tag             node-problem-detector
        Systemd_Filter  _SYSTEMD_UNIT=node-problem-detector.service
        Path            /var/log/journal
        DB              /var/run/google-fluentbit/pos-files/node-problem-detector.db
        Buffer_Max_Size 1MB
        Mem_Buf_Limit   1MB

    [INPUT]
        Name            systemd
        Alias           kube-container-runtime-monitor
        Tag             kube-container-runtime-monitor
        Systemd_Filter  _SYSTEMD_UNIT=kube-container-runtime-monitor.service
        Path            /var/log/journal
        DB              /var/run/google-fluentbit/pos-files/kube-container-runtime-monitor.db
        Buffer_Max_Size 1MB
        Mem_Buf_Limit   1MB

    [INPUT]
        Name            systemd
        Alias           kubelet-monitor
        Tag             kubelet-monitor
        Systemd_Filter  _SYSTEMD_UNIT=kubelet-monitor.service
        Path            /var/log/journal
        DB              /var/run/google-fluentbit/pos-files/kubelet-monitor.db
        Buffer_Max_Size 1MB
        Mem_Buf_Limit   1MB

    [INPUT]
        Name            systemd
        Alias           gcfsd
        Tag             gcfsd
        Systemd_Filter  _SYSTEMD_UNIT=gcfsd.service
        Path            /var/log/journal
        DB              /var/run/google-fluentbit/pos-files/gcfsd.db
        Buffer_Max_Size 1MB
        Mem_Buf_Limit   1MB

    [INPUT]
        Name            systemd
        Alias           gcfs-snapshotter
        Tag             gcfs-snapshotter
        Systemd_Filter  _SYSTEMD_UNIT=gcfs-snapshotter.service
        Path            /var/log/journal
        DB              /var/run/google-fluentbit/pos-files/gcfs-snapshotter.db
        Buffer_Max_Size 1MB
        Mem_Buf_Limit   1MB


    [FILTER]
        Name        modify
        Match       *
        Hard_rename log message

    [FILTER]
        Name         parser
        Match        kube_*
        Key_Name     message
        Reserve_Data True
        Parser       glog
        Parser       json

    [OUTPUT]
        Name        http
        Match       *
        Host        127.0.0.1
        Port        2021
        URI         /logs
        header_tag  FLUENT-TAG
        Format      msgpack
        Retry_Limit 2
  parsers.conf: |-
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

    [PARSER]
        Name        containerd
        Format      regex
        Regex       ^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

    [PARSER]
        Name        json
        Format      json

    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S

    [PARSER]
        Name        glog
        Format      regex
        Regex       ^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source_file>[^ \]]+)\:(?<source_line>\d+)\]\s(?<message>.*)$
        Time_Key    time
        Time_Format %m%d %H:%M:%S.%L%z

    [PARSER]
        Name        network-log
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
kind: ConfigMap
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: fluentbit-gke-config-v1.0.6
  namespace: kube-system
